import React from 'react';
import { useSelector } from 'react-redux';
import addCardRoomGif from '../images/gifs/add-card-rooms.gif';
import dashboardGif from '../images/gifs/dashboard.gif';
import reportGif from '../images/gifs/report.gif';
import signupGif from '../images/gifs/sign-up.gif';
import '../css/about-page.css';
import NavBar from '../components/NavBar';

const AboutPage = () => {
    const { id } = useSelector(state => state.Auth);
    return (
        <>
        {!id && <NavBar />}
        <div className="About-page-page-container">
            {/* <h1>About Page</h1> */}
            <div className="about-page-section section-one">
                <div className="about-section-div 1-1">
                    <h1>What is Jackpot Degen?</h1>
                </div>
                <div className="about-section-div 1-2">
                    <p>Jackpot Degen is an easy-to-use poker room and 
                        bad beat jackpot tracker.  Tired of calling 
                        poker rooms and casinos one-by-one to find out 
                        info on thier current jackpots? We were too! Log 
                        in now to get the latest jackpot updates for your 
                        favorite card rooms and up-to-date poker news.  
                        All jackpots and reviews are user generated by 
                        players like you.  Please report current jackpots 
                        whenever you can to contribute to the community. 
                        Jackpot Degen is free and easy to use.  
                        All we ask is that you are as accurate as 
                        possible when reporting jackpot numbers and leaving 
                        reviews.  We hope you enjoy using Jackpot Degen and we
                        are excited to have you part of the Degen community </p>
                </div>
            </div>
            <div className="about-page-section section-two">
                <div className="about-section-div 2-1">
                    <h1 id="how-to-get-started">How to get started</h1>
                </div>
                <div className="about-section-div 2-2">
                    <div className="about-page-how-to-container">
                        <p className="about-page-how-to-1">Create an account</p>
                        <img className="about-page-how-to-2 create-acount-img" src={signupGif} />
                    </div>
                    <div className="about-page-how-to-container">
                        <img className="about-page-how-to-1 add-rooms-img" src={addCardRoomGif} />
                        <p className="about-page-how-to-2">
                            Search and add all of your favorite poker rooms 
                            in your city or around the country
                        </p>
                    </div>
                    <div className="about-page-how-to-container">
                        <p className="about-page-how-to-1">
                            Get all your jackpot stats and poker news 
                            straight to your dashboard
                        </p>
                        <img className="about-page-how-to-2 dashboard-img" src={dashboardGif} />
                    </div>
                    <div className="about-page-how-to-container">
                        <img className="about-page-how-to-1 report-img" src={reportGif} />
                        <p className="about-page-how-to-2">
                            Report bad beat jackpots while your playing 
                            so others can see and come play with you to make 
                            jackpots larger
                        </p>
                    </div>
                    <div id="about-page-last-step" className="about-page-how-to-container">
                        <p className="about-page-how-to-1 winbig">Always report accurately and WIN BIG!</p>
                        {/* <img className="about-page-how-to-2 win-img" src={logo} /> */}
                    </div>
                </div>
            </div>
            <div className="about-page-section section-three">
                <div className="about-section-div 3-1">

                </div>
                <div className="about-section-div 3-2">

                </div>
            </div>
            <div className="about-page-section section-four">
                <div className="about-section-div 4-1">
                    <h2>Technologies Used</h2>
                </div>
                <div className="about-section-div 4-2">
                    <span>React</span>
                    <span>Redux</span>
                    <span>Express</span>
                    <span>Sequelize</span>
                    <span>PostgreSQL</span>
                </div>
            </div>
        </div>
        </>
    );
};

export default AboutPage